.\" Copyright (c) 2002 Stijn van Dongen
.TH clmconf 1 "22 Feb 2002" "clmconf 1\&.00" "USER COMMANDS"
.SH NAME

clmconf \- create confidence measures for individual nodes and clusters
.SH SYNOPSIS

\fBclmconf\fP <options>

options, all obligatory:

\fB-icl\fP <fname> (\fIinput cluster file\fP)
.br
\fB-imx\fP <fname> (\fIinput matrix/graph file\fP)
.br
\fB-ncm\fP <fname> (\fIoutput node confidence file\fP)
.br
\fB-ccm\fP <name> (\fIoutput cluster confidence file\fP)
.SH DESCRIPTION

\fBclmconf\fP shows how well each node fits in the cluster
it is in and how cohesive each cluster is\&.
This lets you compare the quality of the clusters in a clustering
relative to each other, and may help in identifying both interesting
areas and areas for which cluster structure is hard to find
or perhaps absent\&.

\fBclmconf\fP abuses the \fBmcl\fP matrix format a little
by using it for storing tables\&.

The \fBnode confidence matrix\fP, stored in the file specified by
the \fB-ncm\fP option, has the following structure\&.
The columns range over all elements in the graph as specified
by the \fB-imx\fP option\&. Each row consists of two elements only,
confiding characteristics of \fIc\fP relative to the graph and
the clustering specified by the \fB-icl\fP option\&.
Given a node \fIc\fP,
the entry in row zero shows the mass fraction of edges that have \fIc\fP
as tail and for which the head is in the same cluster as \fIc\fP, relative
to the mass of all edges that have \fIc\fP as tail\&. The entry in row one
lists the number of edges originating from \fIc\fP\&.

The \fBcluster confidence matrix\fP, stored in the file specified by
the \fB-ccm\fP option, has the following structure\&.
The columns range over all clusters in the clustering as specified
by the \fB-icl\fP option\&. Each row consists of two elements\&.
Given a cluster \fIC\fP, the entry in row zero shows the average of the
node confidence (defined above) for all nodes \fIc\fP in \fIC\fP\&. The
entry in row one lists the number of nodes in \fIC\fP\&.
.SH AUTHOR

Stijn van Dongen\&.
.SH SEE ALSO

\fBmcl(1)\fP,
\fBmcx(1)\fP,
\fBclmdist(1)\fP,
\fBclminfo(1)\fP,
\fBclmmeet(1)\fP,
\fBmcx(5)\fP\&.
