.\" Copyright (c) 2002 Stijn van Dongen
.TH mcxconvert 1 "22 Feb 2002" "mcxconvert 1\&.00" "USER COMMANDS"
.SH NAME

mcxconvert \- convert between mcx storage types\&.
.SH SYNOPSIS

\fBmcxconvert\fP <input file name> <output file name>
.SH DESCRIPTION

The \fBmcl\fP libraries make extensive use of matrices\&. Matrices
are used to encode graphs, matrices and clusterings\&.
They can be stored either in ascii or in binary format\&. The latter is
somewhat more efficient in storage and faster in both reading and writing,
but the default is ascii format\&.

The \fBmcl\fP input routines recognize the type of storage they are dealing
with\&. If you want to convert a matrix to the other storage type,
simply specify the file name of the matrix you want to convert\&.
\fBmcxconvert\fP will recognize its type, and write the other type
to the file specified as the second argument\&.

In the future \fBmcxconvert\fP will probably be generalized towards
other objects such as vectors\&.
.SH AUTHOR

Stijn van Dongen\&.
.SH SEE ALSO
\fBmcx(1)\fP,
\fBmcl(1)\fP,
\fBmcx(5)\fP\&.
