# -*- mode: Makefile; -*-
# $Id$

#  Just to make things easier, a toplevel Make that calls the sub-makes


.PHONY: mcl markov

mcl:
	@cd mcl; ${MAKE}; ${MAKE} install

markov:
	@cd markov; ${MAKE}; ${MAKE} install
