#!/usr/local/bin/perl

#
# Quick Perl Script to Fetch a list of sequences from a Database
# -Anton Enright : anton@ebi.ac.uk

$length=$#ARGV;

if ($ARGV[0] eq '')
	{
	print "Fetcher, fetches a list of sequences from a Database\n";
	print "Usage:  fetcher database seq1 seq2 seq3 etc...\n";
	exit(1);
	}

if ($ARGV[0] eq '' || !-e $ARGV[0])
        {
        print "Error: Sequence File not specified or not found\n";
        exit(1);
        }

if ($ARGV[1] eq '')
        {
        print "Error: ID not specified\n";
        exit(1);
        }

if ($ARGV[2] eq '')
        {
        print "Error: Sequences not specified\n";
        exit(1);
        }   

print "Fetching $length Sequences\n";

open (FILE, $ARGV[0]);
open (FILEOUT, "> sequences.$ARGV[1]");

while (<FILE>)
	{
	chop ($_);

	if (substr($_,0,1) eq '>')
		{
		$record=0;

			for ($i=2; $i <= $length ; $i++)
			{	
				/^\>(\S+).*/;
				$query=$1;

				if (substr($_,1,length($query)) eq "$ARGV[$i]")
				{
				$record=1;
				}		
			}

		}

	if ($record==1)
		{
		if (substr($_,0,1) eq '>')
			{
			print "$_ -> Found!\n";
			$total++;
			}
		
		print FILEOUT "$_\n";
		}

	}
print "Found $total Sequences\n";
