#!/usr/local/bin/perl

#
# Quick Perl Script to Fetch a list of sequences from a Database
# -Anton Enright : anton@ebi.ac.uk

use strict;

my  $length= int(@ARGV);

my $Usage=<<END_USAGE;
Fetcher, fetches a list of sequences from a flatfile containing fasta seqs
Usage:  $0 < database.fasta ids > thing.cluster
END_USAGE
;


if (@ARGV==0 ) {
    die $Usage;
}
my $len=int(@ARGV);
warn "Fetching $len sequences\n";

my $total=0;
my $wantthis=0;
while (<STDIN>) {                            # using stdin now
    if ( /^>/ ) {
        my ($id)= ( /^\>(\S+).*/ );
        if (grep( /$id/  , @ARGV) ) {
            $wantthis=1;
            $total++;
            # warn "Found: $_"; 
        } else { 
            $wantthis=0;
        }
    }
    print if $wantthis;
}
warn "Found $total sequences\n";
